NAME = megaphone

SRC = megaphone.cpp
CC = c++
FlAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRC)
	 $(CC) $(SRC) -o $(NAME)

clean:
	

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
